### ISSUE TITLE
void

### ISSUE THREAD

**Issue by lazaridis-com** [lumenitb/lumen-sdk#6]

**Comment by ceefour** [comment]
It contains:

1. the Lumen protocol documentation
2. the different language *client libraries* (*not* modules), which represents Lumen protocol messages (in point 1) in their respective programming languages
3. the *mobile* *app* (which happens to reuse the JavaScript client library in point 2)

**Comment by lazaridis-com** [comment]
See, the only person who sees those things in the source is you (an possibly some of your team members).

In any way, I understand that "a" was the case, so everything is fine.

**Comment by lazaridis-com** [comment]
@ceefour , can you please delete this issue?
